//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eggs2throw.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class movieProfile
    {
        public int movieId { get; set; }
        public string category { get; set; }
        public string name { get; set; }
        public Nullable<int> upVote { get; set; }
        public Nullable<int> downVote { get; set; }
        public string movieLang { get; set; }
        public string review { get; set; }
        public string director { get; set; }
        public string movieCast { get; set; }
        public string songs { get; set; }
        public string link { get; set; }
    }
}
